const calculatorValidator = require("../validators/calculatorValidator.js")

//‚ûï Addition function
const addNumbers = (req, res) => {
    try {
        const { num1, num2 } = req.body
        console.log("üßÆ Ejecutando operaci√≥n: Suma", { num1, num2 })

        let validatorResult = calculatorValidator.validateIntegers(num1, num2)
        let resultNumber = validatorResult.num1 + validatorResult.num2
        
        const response = { 
            data: {
                message: 'Suma realizada correctamente', 
                result: resultNumber
            }
        }

        console.log("‚úÖ Respuesta enviada", response)
        return res.status(200).json(response)
    } catch (error) {
        const errorMessage = error.message
        console.error("‚ùå Error en suma:", errorMessage)

        return res.status(422).json({
            data: {
                message: 'Ocurri√≥ un error al procesar la operaci√≥n',
                error: errorMessage
            }
        })
    }
}

// ‚ûñ Subtract function
const subtractNumbers = (req, res) => {
    try {
        const { num1, num2 } = req.body
        console.log("üßÆ Ejecutando operaci√≥n: Resta", { num1, num2 })

        let validatorResult = calculatorValidator.validateIntegers(num1, num2)
        let resultNumber = validatorResult.num1 - validatorResult.num2
        
        const response = {
            data: {
                message: 'Resta realizada correctamente', 
                result: resultNumber
            }
        }

        console.log("‚úÖ Respuesta enviada:", response)
        return res.status(200).json(response)
    } catch (error) {
        const errorMessage = error.message
        console.error("‚ùå Error en resta:", errorMessage)

        return res.status(422).json({
            data: {
                message: 'Ocurri√≥ un error al procesar la operaci√≥n',
                error: errorMessage
            }
        })
    }
}

// ‚úñ Multiply function
const multiplyNumbers = (req, res) => {
    try {
        const { num1, num2 } = req.body
        console.log("üßÆ Ejecutando operaci√≥n: Multiplicaci√≥n", {num1, num2})

        let validatorResult = calculatorValidator.validateIntegers(num1, num2)
        let resultNumber = validatorResult.num1 * validatorResult.num2
        
        const response = {
            data: {
                message: "Multiplicaci√≥n realizada correctamente",
                result: resultNumber
            }
        }

        console.log("‚úÖ Respuesta enviada:", response)
        return res.status(200).json(response)
    } catch (error) {
        const errorMessage = error.message
        console.log("‚ùå Error en multiplicaci√≥n:", errorMessage)

        return res.status(422).json({
            data: {
                message: 'Ocurri√≥ un error al procesar la operaci√≥n',
                error: errorMessage
            }
        })
    }
}

// ‚ûó Divide function
const divideNumbers = (req, res) => {
    try {
        const { num1, num2 } = req.body
        console.log("üßÆ Ejecutando operaci√≥n: Divisi√≥n", { num1, num2 }) 

        let validatorResult = calculatorValidator.validateIntegers(num1, num2)

        if (validatorResult.num2 === 0) throw new Error("No es posible dividir por cero")
        
        let resultNumber = validatorResult.num1 / validatorResult.num2
        
        const response ={
            data: {
                message: 'C√°lculo hecho correctamente', 
                result: resultNumber
            } 
        }

        console.log("‚úÖ Respuesta enviada:", response)
        return res.status(200).json(response)
    } catch (error) {
        const errorMessage = error.message
        console.error("‚ùå Error en divisi√≥n:", errorMessage)

        return res.status(422).json({
            data: {
                message: 'Ocurri√≥ un error al realizar el c√°lculo',
                error: errorMessage
            }
        })
    }
}

module.exports = { addNumbers, subtractNumbers, multiplyNumbers, divideNumbers }